version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: Install SBCL
          command: sudo apt-get update && sudo apt-get install -y sbcl
      - run:
          name: Install quicklisp
          command: |
            curl -O https://beta.quicklisp.org/quicklisp.lisp
            sbcl --load quicklisp.lisp --eval '(quicklisp-quickstart:install)'
      - run:
          name: Run tests
          command: sbcl --script run-circleci.lisp
